name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      NODE_ENV: development
      DB_HOST: localhost
      DB_USER: myusername
      DB_PASS: mypassword
      DB_NAME: cicdtest
      PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start MySQL
        run: sudo systemctl start mysql

      - name: Create database
        run: mysql -u root -proot < db/create-db.sql

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ env.DB_HOST }}" >> .env
          echo "DB_USER=${{ env.DB_USER }}" >> .env
          echo "DB_PASS=${{ env.DB_PASS }}" >> .env
          echo "DB_NAME=${{ env.DB_NAME }}" >> .env
          echo "PORT=${{ env.PORT }}" >> .env

      - name: Run tests
        run: npm test
